export const LANG_MAP = new Map([
    ['Chinese (Hong Kong)', 'zh-hk'],
    ['Czech', 'cs'],
    ['Danish', 'da'],
    ['English', 'en'],
    ['Greek', 'el'],
    ['Hindi', 'hi'],
    ['Irish', 'ga'],
    ['Japanese', 'ja'],
    ['Korean', 'ko'],
    ['Malayalam', 'ml'],
    ['Polish', 'pl'],
    ['Punjabi', 'pa'],
    ['Romanian', 'ro'],
    ['Russian', 'ru'],
    ['Serbian', 'sr'],
    ['Slovak', 'sk'],
    ['Slovenian', 'sl'],
    ['Sorbian', 'sb'],
    ['Swedish', 'sv'],
    ['Urdu', 'ur'],
]);